<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TourDuLich.Application\TourDuLich.Application.csproj" />
    <ProjectReference Include="..\TourDuLich.Infrastructure\TourDuLich.Infrastructure.csproj" />
    <ProjectReference Include="..\TourDuLich.Domain\TourDuLich.Domain.csproj" />
  </ItemGroup>

</Project>
